sudo: required
services:
  - docker

before_install:
  - docker build -t benaroh30/server -f Dockerfile.dev .

script:
  - docker run benaroh30/server npm test -- --coverage

after_success:
  - openssl enc -aes256 -d -in serviceAccount.json.enc -out serviceAccount.json -k $SERVICE_KEY
  
  # Install GCP SDK and update to the latest version
  - if [ -d "$HOME/google-cloud-sdk" ]; then rm -rf $HOME/google-cloud-sdk; fi
  - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - curl -sSL https://sdk.cloud.google.com | bash
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud components update
  - gcloud components install beta gcloud-pubsub-emulator alpha cloud-build-local
  - gcloud auth activate-service-account --key-file serviceAccount.json
  - gcloud config set project eshop-438818
  - gcloud config set compute/zone us-west2-a

  # Decrypt environment variables
  - openssl enc -aes256 -d -in .enc -out .env -k $SECRET_KEY

  # Build production docker image
  - docker build -t benaroh30/server .
  - echo "$Docker_password" | docker login --username "$Docker_id" --password-stdin
  - docker push benaroh30/server
  - bash ./deploy.sh
