sudo: required
services:
  - docker
before_install:
  - docker build -t benaroh30/server -f Dockerfile.dev .
script:
  - docker run benaroh30/server npm test -- --coverage
after_success:
#Decrypt environment variables
  - openssl enc -aes256 -d -in .enc -out .env -k $SECRET_KEY
  #build production dockerfile
  - docker build -t benaroh30/server .
  - echo "$Docker_password" | docker login --username "$Docker_id" --password-stdin
  - docker push benaroh30/server